version: '3.1'

services:
  postgres:
    image: postgres:13.0
    container_name: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  activeMQ:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    ports:
      - "60000:61616"
      - "8161:8161"